import 'package:drift/drift.dart';
import 'package:reebaplus_pos/shared/models/order.dart' as domain;
import 'package:reebaplus_pos/core/database/app_database.dart';

class OrderService {
  final _ordersDao = database.ordersDao;

  OrderService();

  Future<String> addOrder({
    required int? customerId,
    required List<Map<String, dynamic>> cart,
    required int totalAmountKobo,
    required int amountPaidKobo,
    required String paymentType,
    int? staffId,
    int? warehouseId,
    int crateDepositPaidKobo = 0,
    String paymentSubType = 'cash', // 'cash' or 'wallet'
  }) async {
    final resolvedWarehouseId = warehouseId ?? 1;
    final resolvedStaffId = staffId ?? 1;

    final order = OrdersCompanion.insert(
      orderNumber: '', // Generated by DAO but required here for insert
      customerId: Value(customerId),
      totalAmountKobo: totalAmountKobo,
      netAmountKobo: totalAmountKobo, // Assuming no discount for now
      amountPaidKobo: Value(amountPaidKobo),
      paymentType: paymentType,
      status: 'pending',
      createdAt: Value(DateTime.now()),
      staffId: Value(resolvedStaffId),
      warehouseId: Value(resolvedWarehouseId),
      crateDepositPaidKobo: Value(crateDepositPaidKobo),
    );

    final items = cart.map((item) {
      final price = (item['price'] as num).toDouble();
      final qty   = (item['qty']   as num).toDouble();
      return OrderItemsCompanion.insert(
        orderId: 0, // Set by DAO
        productId: (item['id'] as int?) ?? 0,
        warehouseId: resolvedWarehouseId,
        quantity: qty.toInt(),
        unitPriceKobo: (price * 100).round(),
        buyingPriceKobo: Value(item['buyingPriceKobo'] as int? ?? 0),
        totalKobo: (price * qty * 100).round(),
      );
    }).toList();

    final orderNo = await _ordersDao.createOrder(
      order: order,
      items: items,
      customerId: customerId,
      amountPaidKobo: amountPaidKobo,
      totalAmountKobo: totalAmountKobo,
      staffId: resolvedStaffId,
    );

    await _recordWalletTransactions(
      customerId: customerId,
      orderNo: orderNo,
      paymentType: paymentType,
      paymentSubType: paymentSubType,
      totalAmountKobo: totalAmountKobo,
      amountPaidKobo: amountPaidKobo,
      staffId: resolvedStaffId,
    );

    return orderNo;
  }

  Future<void> _recordWalletTransactions({
    required int? customerId,
    required String orderNo,
    required String paymentType,
    required String paymentSubType,
    required int totalAmountKobo,
    required int amountPaidKobo,
    required int staffId,
  }) async {
    if (customerId == null) return; // Walk-in: no customer wallet

    final dao = database.customersDao;

    if (paymentType == 'Full Cash / Card' && paymentSubType != 'wallet') {
      // Audit trail only — cash in, sale out, net zero
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: totalAmountKobo,
        type: 'credit', referenceId: orderNo, staffId: staffId,
        note: 'cash_received',
      );
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: totalAmountKobo,
        type: 'debit', referenceId: orderNo, staffId: staffId,
        note: 'sale_charged',
      );

    } else if (paymentType == 'Wallet Payment') {
      // Deduct full amount from wallet
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: totalAmountKobo,
        type: 'debit', referenceId: orderNo, staffId: staffId,
        note: 'wallet_payment',
      );

    } else if (paymentType == 'Partial Cash / Card') {
      // Credit what was paid; debit the full amount
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: amountPaidKobo,
        type: 'credit', referenceId: orderNo, staffId: staffId,
        note: 'partial_cash',
      );
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: totalAmountKobo,
        type: 'debit', referenceId: orderNo, staffId: staffId,
        note: 'sale_charged',
      );

    } else if (paymentType == 'Credit Sale') {
      // Full amount owed — debit everything
      await dao.recordWalletTransaction(
        customerId: customerId, amountKobo: totalAmountKobo,
        type: 'debit', referenceId: orderNo, staffId: staffId,
        note: 'credit_sale',
      );
    }
    // Unrecognised paymentType → no entries (safe fallback)
  }

  Stream<List<domain.Order>> watchPendingOrders() {
    return _ordersDao
        .watchPendingOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<domain.Order>> watchAllOrders() {
    return _ordersDao
        .watchAllOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<domain.Order>> watchCompletedOrders() {
    return _ordersDao
        .watchCompletedOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<OrderWithItems>> watchAllOrdersWithItems() {
    return _ordersDao.watchAllOrdersWithItems();
  }

  static domain.Order fromDb(OrderData data) {
    return domain.Order(
      id: data.id.toString(),
      customerId: data.customerId?.toString(),
      customerName: 'Customer ${data.customerId}',
      items: [],
      totalAmount: data.totalAmountKobo / 100.0,
      amountPaid: data.amountPaidKobo / 100.0,
      customerWallet: 0.0,
      paymentMethod: data.paymentType,
      createdAt: data.createdAt,
      status: data.status,
    );
  }

  Future<void> markAsCompleted(int orderId, int staffId) {
    return _ordersDao.markCompleted(orderId, staffId);
  }

  Future<void> markAsCancelled(int orderId, String reason, int staffId) {
    return _ordersDao.markCancelled(orderId, reason, staffId);
  }

  Future<void> assignRider(int orderId, String riderName) {
    return _ordersDao.assignRider(orderId, riderName);
  }

  Future<List<UserData>> getRiders() {
    return database.warehousesDao.getRiders();
  }
}

final orderService = OrderService();
