import 'package:drift/drift.dart';
import '../models/order.dart' as domain;
import '../../core/database/app_database.dart';

class OrderService {
  final _ordersDao = database.ordersDao;

  OrderService();

  Future<String> addOrder({
    required int? customerId,
    required List<Map<String, dynamic>> cart,
    required int totalAmountKobo,
    required int amountPaidKobo,
    required String paymentType,
    int? staffId,
    int? warehouseId,
    int crateDepositPaidKobo = 0,
  }) async {
    final resolvedWarehouseId = warehouseId ?? 1;

    final order = OrdersCompanion.insert(
      orderNumber: '', // Generated by DAO but required here for insert
      customerId: Value(customerId),
      totalAmountKobo: totalAmountKobo,
      netAmountKobo: totalAmountKobo, // Assuming no discount for now
      amountPaidKobo: Value(amountPaidKobo),
      paymentType: paymentType,
      status: 'pending',
      createdAt: Value(DateTime.now()),
      staffId: Value(staffId ?? 1),
      warehouseId: Value(resolvedWarehouseId),
      crateDepositPaidKobo: Value(crateDepositPaidKobo),
    );

    final items = cart.map((item) {
      final price = (item['price'] as num).toDouble();
      final qty   = (item['qty']   as num).toDouble();
      return OrderItemsCompanion.insert(
        orderId: 0, // Set by DAO
        productId: (item['id'] as int?) ?? 0,
        warehouseId: resolvedWarehouseId,
        quantity: qty.toInt(),
        unitPriceKobo: (price * 100).round(),
        totalKobo: (price * qty * 100).round(),
      );
    }).toList();

    return await _ordersDao.createOrder(
      order: order,
      items: items,
      customerId: customerId,
      amountPaidKobo: amountPaidKobo,
      totalAmountKobo: totalAmountKobo,
      staffId: staffId ?? 1,
    );
  }

  Stream<List<domain.Order>> watchPendingOrders() {
    return _ordersDao
        .watchPendingOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<domain.Order>> watchAllOrders() {
    return _ordersDao
        .watchAllOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<domain.Order>> watchCompletedOrders() {
    return _ordersDao
        .watchCompletedOrders()
        .map<List<domain.Order>>(
          (list) => list.map<domain.Order>((d) => OrderService.fromDb(d)).toList(),
        );
  }

  Stream<List<OrderWithItems>> watchAllOrdersWithItems() {
    return _ordersDao.watchAllOrdersWithItems();
  }

  static domain.Order fromDb(OrderData data) {
    return domain.Order(
      id: data.id.toString(),
      customerId: data.customerId?.toString(),
      customerName: 'Customer ${data.customerId}',
      items: [],
      totalAmount: data.totalAmountKobo / 100.0,
      amountPaid: data.amountPaidKobo / 100.0,
      customerWallet: 0.0,
      paymentMethod: data.paymentType,
      createdAt: data.createdAt,
      status: data.status,
    );
  }

  Future<void> markAsCompleted(int orderId, int staffId) {
    return _ordersDao.markCompleted(orderId, staffId);
  }

  Future<void> markAsCancelled(int orderId, String reason, int staffId) {
    return _ordersDao.markCancelled(orderId, reason, staffId);
  }

  Future<void> assignRider(int orderId, String riderName) {
    return _ordersDao.assignRider(orderId, riderName);
  }

  Future<List<UserData>> getRiders() {
    return database.warehousesDao.getRiders();
  }
}

final orderService = OrderService();
